apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  serviceName: not-applicable
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mariadb/
              name: mariadbdata
          envFrom:
            - secretRef:
                name: mariadb-secret
      volumes:
        - name: mariadbdata
          persistentVolumeClaim:
            claimName: mariadb-pvc
